### PR TITLE
Fix unknown_functional setting in deserialized Structure instances

### LINKED ISSUE #618: deepcopy(Structure()) behavior and pickling methods
@ChayaSt noticed that, if you `copy.deepcopy` a `Structure` instance, `.createSystem()` on the copy fails because the `.unknown_functional` attribute does not exist: https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L1808

Of course I got obsessed over this and had to work out what was going on. My understanding here is that, as `Structure` doesn't have a `__deepcopy__` method, `copy.deepcopy(Structure())` will fall back to using the `__getstate__` and `__setstate__` pickling methods. And those happen to be missing the `unknown_functional` attribute, as well as the `space_group`. 

For the copying I guess you could just say - just use `copy.copy` because the `__copy__` method provides deep copying behavior. But for pickling this is definitely a bug it seems, you're getting a broken Structure after pickling-unpickling.

### PR DESCRIPTION
**Pull request by swails**
Fixes #618 

@ChayaSt and @rafwiewiora -- can you check that this fixes the deepcopy issues you were seeing?

### CODE REVIEW

**Comment by rafwiewiora** [comment]
@ChayaSt can you check your script's working now? 

@swails just wondering if you missed where I said in the issue that `space_group` was missing too or is that not worth adding?

**Comment by swails** [comment]
I missed it, sorry. I'll issue a PR tonight.

**Comment by rafwiewiora** [comment]
Alright!

**Comment by ChayaSt** [comment]
It's working now!
Thanks @rafwiewiora  for tracking this down and @swails for fixing it!

**Pull request merged**
