### PR TITLE
from pyrosetta import Pose

### PR DESCRIPTION
**Pull request by hainm**
```bash
UserWarning: Import of 'rosetta' as a top-level module is deprecated
```
(Actually "from rosetta import Pose, init" does not work anymore)

I am using 2016 version  (pyrosetta-4.0) (for testing nglview):
pose

### CODE REVIEW

**Comment by hainm** [comment]
init

**Comment by hainm** [comment]
Uhm, there's something wrong with `parmed.rosetta` code. The tests just hang in there.
screen shot 2017-07-26 at 1 33 59 am

cc @cxhernandez

**Comment by hainm** [comment]
Uhm, may be something wrong with `pyrosetta 4.0` on MacOS. Not sure.

**Comment by cxhernandez** [comment]
I haven't tested the ParmEd code with PyRosetta v4 yet. When they released v4 last year, I was curious to try it out but there wasn't any documentation and the API seemed to have changed a bit. 

I can try to take a look at it sometime this week, but, in the meantime, I'd recommend using v3.

**Comment by hainm** [comment]
close for now.

**Pull request closed without merging**
