### PR TITLE
Expand meaning of write_unused to removing templates using unavailable atom types

### PR DESCRIPTION
**Pull request by rafwiewiora**
This for #627.

### CODE REVIEW

**Comment by rafwiewiora** [comment]
Ok, first commit was a bad idea - it was removing those residues from ParameterSet rather than just not write, forget that. 

I just did it analogically to the type skipping in second commit.

**Comment by rafwiewiora** [comment]
2 Pyflakes failures look unrelated to this?

**Comment by swails** [comment]
Oh come on pyflakes!  It's an upstream change that broke the checks.  That change truly sucks.  I think the problem here is that pyflakes is being upgraded to 1.1.  Can you try to pin it at 1.0.0?  It's installed via pip for pypy and conda for everything else.  Just modify install.sh to pin the versions.  For pip, this would look like

```
pypy -m pip install pyflakes==1.0.0
```

For conda it would look like

```
conda install pyflakes=1.0.0
```

Hopefully that fixes it.

**Comment by swails** [comment]
Also, can you add a test for this?

**Comment by rafwiewiora** [comment]
Ok, I'm on it!

**Comment by rafwiewiora** [comment]
Test added, pyflakes fixed to 1.0.0 (I didn't want to list all packages in the update call again instead of --all so I moved pyflakes to a separate line there). 

Had to add atomic_ions.lib to the test/files, that ok?

**Comment by swails** [comment]
Looks good! Thanks for all the work. I'll merge after Travis passes

**Comment by rafwiewiora** [comment]
Sorry didn't manage to write this before you merged - at a tech conference with no wifi and no signal...

I had to filter warnings in the test function: `warnings.filterwarnings('ignore', category=exceptions.ParameterWarning)` because otherwise it was failing the tests there - I don't understand this fully: are the warnings filtered to error in the tests? And should my test filter it back to 'default' or 'always' or does it get reset between functions?

**Comment by swails** [comment]
When I want to test that a warning is properly triggered, I always put in a `filterwarnings('error', category=WhateverWarning)`, do an `assertRaises`, and then ignore them to test what happens when the warning is ignored.  So what you did is fine.

**Comment by swails** [comment]
I really should move to using `nose`, that has an explicit `assert_warns` method (I don't think `unittest` for Python 2.7 has an `assertWarns` -- I've tried it before IIRC).

**Comment by rafwiewiora** [comment]
Alright, thanks!

**Pull request merged**
