### PR TITLE
Give an option of skipping setuptools, since it doesn't work nicely w…

### PR DESCRIPTION
**Pull request by swails**
…ith how

AmberTools sometimes installs Python modules.

### CODE REVIEW

**Comment by hainm** [comment]
What is your reason to switch to setuptools? Parmed worked fine before and it does not require external package for install.

**Comment by swails** [comment]
Setup tools allows the use of entry points for automatic script generation and it knows how to play nicely with Windows. The disutils based install does not create Windows runnable scripts. 

Also, pip complains if you don't use setuptools since distutils doesn't create a package that pip knows how to uninstall. And supporting pip is important to me.

**Comment by hainm** [comment]
just tested on amber repo. works fine with me.

**Comment by swails** [comment]
Thanks!

**Comment by hainm** [comment]
I just realize that if we `source amber.sh` before installing ParmEd with setuptools, thing will be fine; because $AMBERHOME/lib/ would be added to PYTHONPATH. :D

**Comment by hainm** [comment]
**updated**: nvm about above comment.

**Pull request merged**
