### PR TITLE
Change imports from chemistry -> parmed and ParmedTools -> parmed.tools

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by swails** [comment]
OK.  This reorganization is finished as described in #85 (and #169).  This represents a major API breakage, with the major differences detailed below:

- `chemistry` package renamed to `parmed`
- `ParmedTools` package moved to `tools` subpackage in `parmed`
- `ParmedTools.ParmedActions` module was renamed to `actions` in the `parmed.tools` package
- `fortranformat` package was moved into `parmed.utils` (but this is only used internally for the AmberParm class).
- Got rid of the redundant (and deprecated) `openmmloader` modules in the `amber` and `charmm` packages (I don't think anybody was using them)

I also took this opportunity to clean up the exception hierarchy and stem the proliferation of exceptions.  I can probably reduce this a little bit more, but it's good for now.

I also added a Raises section to the docstrings of more functions to indicate what possible exceptions may be raised.

Finally, the `setup.py` script will look through all directories in `sys.path` and remove any `chemistry` or `ParmedTools` packages that are present.

The summary of changes necessary to adapt to this new version are:

```Python
import chemistry
# replaced by
import parmed

from chemistry import foo, bar
# replaced by
from parmed import foo, bar

import ParmedTools
# replaced by
import parmed.tools

import ParmedTools.ParmedActions
# replaced by
import parmed.tools.actions
```

Easy fixes are:

```Python
import parmed as chemistry # exactly replaces "import chemistry"
import parmed.tools as ParmedTools # exactly replaces "import ParmedTools"
```

Or in cases where you do `from chemistry import <stuff>`, just replace `chemistry` with `parmed`.

**Comment by hainm** [comment]
+1

**Comment by davidlmobley** [comment]
@swails - could you make a new version tag for this, perhaps v2.0 beta1 or something? I would like to specify what version of ParmEd is required for `openmoltools` and currently I have to say something complicated (v2.0 beta after update #173 or something along those lines).

**Comment by swails** [comment]
You mean cut a new pre-release?  The `parmed.__version__` tag already says "2.0beta1".

**Comment by davidlmobley** [comment]
"Cut a new pre-release" was what I meant, but if you incremented the
version tag at the same time as this change, that would be adequate since
then I can just say 2.0beta1. Is that what happened?

**Comment by swails** [comment]
Done.

**Pull request merged**
