### PR TITLE
Try to migrate to using Travis's container-based system

### PR DESCRIPTION
**Pull request by swails**
Should give faster builds and more memory (!!)

### CODE REVIEW

**Comment by hainm** [comment]
@swails can you  briefly tell about this? "Try to migrate to using Travis's container-based system"

**Comment by swails** [comment]
See https://github.com/omnia-md/omnia-md/issues/16#issuecomment-120420397 where I detailed my experiences with ParmEd as well as Travis's webpage: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

You can see that link yourself in a message that pops up at the top of the Travis build website for pytraj.  See https://travis-ci.org/pytraj/pytraj/jobs/70357487 for instance.

**Comment by hainm** [comment]
thanks.

**Comment by hainm** [comment]
ah, so 134 files are those test files you wanted to add before (but couldn't due to memory)?

**Comment by swails** [comment]
No, no.  Those 134 test files I had to add because `sudo apt-get install gromacs` doesn't work anymore.  Which means I could no longer rely on Gromacs topology files being present on the Travis build environment.  So I had to add them to my repository to keep Travis happy.

What occasionally happened to me before was that random builds in my build matrix would get killed, presumably because all 4 jobs would just happen to line up such that their combined memory usage was over the allowed limit, so one of them would get killed.  This is much less likely to happen to me now since (a) the containers have 33% more RAM available to them and (b) I removed one of the builds from my build matrix.

**Comment by hainm** [comment]
so why don't you git clone their repo on travis?

**Comment by swails** [comment]
Because all I need are ~1MB of parameter files

**Comment by hainm** [comment]
I see. thanks.

**Comment by rmcgibbo** [comment]
Gromacs is now available on travis: https://github.com/travis-ci/apt-package-whitelist/pull/695

**Comment by swails** [comment]
Thanks!

**Pull request merged**
