### PR TITLE
Fixed compatibility with NumPy 2.0+

### PR DESCRIPTION
**Pull request by vedranmiletic**
Issue #1364

### CODE REVIEW

**Comment by vedranmiletic** [comment]
I would appreciate pointers how to improve numerical accuracy with Python versions older than 3.12.

**Comment by swails** [comment]
*sigh*, that's a lazy test, apologies.

Can you just change the test so it checks that they're not all zero?

**Comment by swails** [comment]
I fixed the tests in #1370 and updated this branch. It should hopefully pass tests and I can merge this PR.

**Comment by vedranmiletic** [comment]
Wow, that was quick, thanks!

**Pull request merged**
