### PR TITLE
Add cphmd/cemd limits section to cpin/cein

### PR DESCRIPTION
**Pull request by swails**
- [x] Tests need to be updated for this (they will fail)
- [x] We need to make sure a cpin file generated from here runs in "old" versions of Amber
- [x] We need to make sure this functionality "works"

### CODE REVIEW

**Comment by swails** [comment]
@vwcruzeiro - proposed changes here

**Comment by vwcruzeiro** [comment]
> We need to make sure a cpin file generated from here runs in "old" versions of Amber

I have tested this. The new namelist will be ignored in older versions of Amber, exactly what we want.

**Comment by vwcruzeiro** [comment]
@swails I have tested your changes, and all is good. Please change line 381 in titratable_residues to:
`if (typ != "redox"): limit_buf.add_word(' maxh=%d,' % max(len(r.states) for r in self))`
We do not need maxh for CEIN files.

Thanks!

**Comment by swails** [comment]
If it doesn't hurt as-is, let's just keep it. The fewer branches we can get away with the better.

**Comment by vwcruzeiro** [comment]
> If it doesn't hurt as-is, let's just keep it. The fewer branches we can get away with the better.

Ok. If we keep it, the code will still run. maxh will be read by pmemd/sander, but will be ignored at constante.F90

**Comment by swails** [comment]
It needs to be in the name list in for conste. Otherwise reading it will fail.

**Comment by vwcruzeiro** [comment]
maxh is in the namelist at constante.F90, so we are good.

**Comment by swails** [comment]
Finally :/

**Pull request merged**
