### PR TITLE
[WIP] Urey Bradley term fix

### PR DESCRIPTION
**Pull request by ChayaSt**
The changes in this PR adds the middle atom to the ```structure.urey_bradleys``` list.

This is not working yet because of [this](https://github.com/ParmEd/ParmEd/issues/665#issuecomment-207151978)

I'm not sure if these changes are the best way to handle this.

### CODE REVIEW

**Comment by swails** [comment]
I really don't think we should add `atom3` to `UreyBradley`.  There are *so* many places this would require changing that it would be a huge job.  Not to mention the fact that it represents an API break.  Furthermore, Urey-Bradley terms really *are* 2-body terms, and the current data structure highlights that fact.  Lastly, it's easy to get the central atom from `atom1` and `atom2` -- [see here](https://github.com/swails/ParmEd/blob/ureybrad/parmed/parameters.py#L478).

The main problem we're trying to solve here is how do we key and match Urey-Bradley terms.  The easiest and safest way to do that is with 3 atom types, and that was being done in the CHARMM code, but not the GROMACS code.

Give #666 a try and see if that works for you.  I also added what I hope is a fix for [the issue you already mentioned](https://github.com/ParmEd/ParmEd/issues/665#issuecomment-207151978).

**Comment by ChayaSt** [comment]
> I really don't think we should add atom3 to UreyBradley. There are so many places this would require changing that it would be a huge job. Not to mention the fact that it represents an API break. Furthermore, Urey-Bradley terms really are 2-body terms, and the current data structure highlights that fact. Lastly, it's easy to get the central atom from atom1 and atom2 -- see here.

I agree with you. I merged your changes into my branch and will work with that.

**Comment by swails** [comment]
I *just* pushed the fix to the missing Urey-Bradleys.  I'm not sure when you merged my branch in, but if it wasn't within the last 5 minutes, can you do it again?

**Comment by swails** [comment]
Ack, I just pushed a fix to the missing U-B "fix".  I think it should work now.

**Comment by ChayaSt** [comment]
Yes, it's working now. Thanks!

**Comment by ChayaSt** [comment]
Closing this PR. https://github.com/ParmEd/ParmEd/pull/666 fixes this.

**Pull request closed without merging**
