### PR TITLE
First pass at getting Jenkins working.

### PR DESCRIPTION
**Pull request by swails**
Just trying things out...

### CODE REVIEW

**Comment by jchodera** [comment]
Are you using a cloud installation of Jenkins, or a physical Jenkins server?

**Comment by swails** [comment]
The single greatest Jenkins server in existence

**Comment by swails** [comment]
:)

**Comment by jchodera** [comment]
?

**Comment by swails** [comment]
http://www.jasonswails.com:8888/job/ParmEd/job/ParmEd/job/PR-808/2/

**Comment by hainm** [comment]
give us your password too :)) (j/k)

**Comment by jchodera** [comment]
Please tell me this server is running on an intelligent dimmer switch...

**Comment by swails** [comment]
> Please tell me this server is running on an intelligent dimmer switch...

Of course it is -- how else am I supposed to test slow computers?

**Pull request closed without merging**
