### PR TITLE
Add support for Amber's CMake build system

### PR DESCRIPTION
**Pull request by multiplemonomials**
This is fairly straightforward.  The only thing I had to do was add a CMake script and make `setup.py` pass a couple extra flags for building on 64-bit MinGW.  Seriously, someday I'd like to have long, harsh words with the people who wrote Distutils's MinGW support, ending in a slap to the face.

My only other thing is that whenever I build ParmEd on my Windows machine, it runs some kind of Git command that takes about 5 minutes to complete, to the point where it holds up the rest of the build. This is not uncommon; git operations take about an order of magnitude longer on Windows and Windows Subsystem for Linux, but it would be really nice if there was some way to turn it off.  On second thought, it might not be a problem with the new submodule setup; I'll have to check.

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
It's using git to pull out the version from the closest tag. Something like 

git describe

**Comment by hainm** [comment]
@multiplemonomials 

I am not sure it's worth effort supporting MinGW. For Python, I would prefer to have AMBER python packages work with Miniconda (and conda) ecosystem.

FYI: https://mingwpy.github.io/
(not sure if it's still actively developed)

**Comment by multiplemonomials** [comment]
wait, what?  Why did it fail?  It looks like it's trying to access a file from a server that isn't there???

**Comment by multiplemonomials** [comment]
I think that supporting MinGW on Windows *is* supporting Miniconda on Windows

**Comment by hainm** [comment]
I am not sure. Please check here: https://conda.io/docs/build_tutorials/windows.html

**Comment by multiplemonomials** [comment]
Bluh, Visual Studio.  The thing is, I have to make the Amber build system work with MinGW if I want Windows support at all.  First of all, if you want a Fortran compiler that works on Windows, you have to pay an arm and a leg to Intel for their Composer XE software, and second of all, MSVC can't compile many of Amber's C programs because they rely on the low level of POSIX compatibility that MinGW provides.  All I know is that I have successfully used MinGW-W64 to compile ParmEd and Pytraj so that they work with Miniconda

**Comment by hainm** [comment]
>All I know is that I have successfully used MinGW-W64 to compile ParmEd and Pytraj so that they work with Miniconda

It's still a puzzle to me about this. If this is true, it's still really cool. We only need to distribute amber binary or installer.

**Comment by hainm** [comment]
Sorry about my English. For your above sentence, do you mean you are "assuming" or did you try pytraj with Python from Miniconda? (e:g: python -c "import sys; print(sys.prefix); import pytraj; pytraj.run_tests()"

**Comment by multiplemonomials** [comment]
Yeah, I can.  It loads but doesn't work though
```

C:\Program Files\Amber 17.0.0>miniconda\python.exe -c "import sys; print(sys.prefix); import pytraj;
 pytraj.run_tests()"
C:\Program Files\Amber 17.0.0\miniconda
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Amber 17.0.0\lib\site-packages\pytraj\__init__.py", line 23, in <module>
    from .utils.misc import info
  File "C:\Program Files\Amber 17.0.0\lib\site-packages\pytraj\utils\misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "C:\Program Files\Amber 17.0.0\lib\site-packages\pytraj\core\__init__.py", line 2, in <module
>
    from .topology_objects import Atom, Residue, Molecule
ImportError: No module named topology_objects
```

This was an old installation built from whatever was in Amber's master branch in early May

**Comment by hainm** [comment]
That means it can not be used with python from miniconda. Make senses to me since its Python built by Visual Studio.

**Comment by multiplemonomials** [comment]
ParmEd works though:
```
C:\Program Files\Amber 17.0.0>miniconda\python.exe -c "import parmed; from parmed.scripts import cla
pp; clapp()"

.     .       .  .   . .   .   . .    +  .
  .     .  :     .    .. :. .___---------___.
       .  .   .    .  :.:. _".^ .^ ^.  '.. :"-_. .
    .  :       .  .  .:../:            . .^  :.:\.
        .   . :: +. :.:/: .   .    .        . . .:\
 .  :    .     . _ :::/:               .  ^ .  . .:\
  .. . .   . - : :.:./.                        .  .:\
  .      .     . :..|:                    .  .  ^. .:|
    .       . : : ..||        .                . . !:|
  .     . . . ::. ::\(                           . :)/
 .   .     : . : .:.|. ######              .#######::|
  :.. .  :-  : .:  ::|.#######           ..########:|
 .  .  .  ..  .  .. :\ ########          :######## :/
  .        .+ :: : -.:\ ########       . ########.:/
    .  .+   . . . . :.:\. #######       #######..:/
      :: . . . . ::.:..:.\           .   .   ..:/
   .   .   .  .. :  -::::.\.       | |     . .:/
      .  :  .  .  .-:.":.::.\             ..:/ .~~~~~~~~~~~.
 .      -.   . . . .: .:::.:.\.           .:/,: Prepare to  \
.   .   .  :      : ....::_:..:\   ___.  :/ .       be       |
   .   .  .   .:. .. .  .: :.:.:\       :/   \  P A R M E D |
     +   .   .   : . ::. :.:. .:.|\  .:/|      \~~~~~~~~~~~'
     .         +   .  .  ...:: ..|  --.:|
.      . . .   .  .  . ... :..:.."(  ..)"
 .   .       .      :  .   .: ::/  .  .::\

ParmEd: a Parameter file Editor


Could not open logfile. Skip logging
Reading input from STDIN...
>
```

**Comment by hainm** [comment]
ParmEd is different thing. It's almost pure Python so it should work everywhere. 

pytraj has C++ generated code from cython.

**Comment by multiplemonomials** [comment]
I don't know a ton about python, but doesn't that look like some kind of error about not having a package installed?   I figured that a binary-level error would look more... binary

**Comment by hainm** [comment]
> I figured that a binary-level error would look more... binary

yeah.

> I don't know a ton about python

Python is sometimes weird.

**Comment by multiplemonomials** [comment]
hang on a minute.  I just discovered that the .pyd files did not get copied from the build directory to the install directory!  I coped them manually, and now I'm getting a different error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jamie\Documents\amber-install\lib\site-packages\pytraj\__init__.py", line 23, in <m
odule>
    from .utils.misc import info
  File "C:\Users\Jamie\Documents\amber-install\lib\site-packages\pytraj\utils\misc.py", line 7, in <
module>
    from pytraj.core.c_options import set_world_silent
  File "C:\Users\Jamie\Documents\amber-install\lib\site-packages\pytraj\core\__init__.py", line 2, i
n <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: DLL load failed: The specified module could not be found.

```

**Comment by multiplemonomials** [comment]
...and Process Monitor reveals that it's failing to find `libcpptraj.dll`, which is missing from the bin directory

**Comment by hainm** [comment]
it should be in $AMBERHOME/lib (not bin), right?

**Comment by hainm** [comment]
We should move discussion about pytraj-related issue to its repo https://github.com/Amber-MD/pytraj/pull/1408

(to avoid spamming ParmEd and to keep track in the future).

**Comment by multiplemonomials** [comment]
Nope, on Windows, DLLs go into bin because they have to be on the PATH.  It's weird, I know.  It looks like I made a mistake in the build system that was causing `libcpptraj.dll` to not get installed.  I copied it manually, and now I get 

```
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```

This one looks a little harder to deal with

**Comment by hainm** [comment]
Enjoy working on Windows. I gave up long time ago. :D

**Comment by swails** [comment]
The test failures here are caused because the PDB seems to have changed one of their files.  I submitted a PR that updates the test file so it will pass.  Once that is merged, you can update this PR and it should pass.

Also, ParmEd makes no use of `libcpptraj`, so I'm not sure what problem that could be causing here (but it should not be related to ParmEd specifically).

**Comment by multiplemonomials** [comment]
Sorry, Hai and me were talking about pytraj on the wrong PR.  `libcpptraj` doesn't have anything to do with ParmEd

**Comment by swails** [comment]
run jenkins

**Pull request merged**
