### PR TITLE
Add a bunch of tests and fix a couple issues

### PR DESCRIPTION
**Pull request by swails**
This PR is opened to fix the issues raised in #593, but also adds a bunch of tests I've been sitting on for the actions.py module.

TODO:

- [x] Issue 1 (blank lines in lib files)
- [x] Issue 2 (Wonky whitespace delimiters in frcmod/dat files)
- [x] Issue 3 (Weird connectivity)
- [x] Issue 4 (expose `oldff` somehow)
- [x] Fix reading GLYCAM parameter files [NEW]

### CODE REVIEW

**Comment by swails** [comment]
OK, the only thing left to do here is expose `lib/oldff` if this is actually needed.  But is it?  There's nothing I see in that folder that would be worth using as far as I can tell.  The newest thing there is ff91, and that's before the scaling factors were set to 1.2 and 2.0.  The current FF lineage started at FF94 (that was the original Cornell et al. work).  FF91 was a completely different beast.

And actually, everything FF91 and older uses a 10-12 potential on some atom pairs, and that FF is only supported in OpenMM through ParmEd's AmberParm (`AmberPrmtopFile` in OpenMM chokes on it -- not even sure if it raises an exception to be honest, but it certainly doesn't implement the 10-12 potential).

**Comment by jchodera** [comment]
We can add the 10-12 potential as a `CustomNonbondedForce`.  How is that represented in `AmberParameterSet`?

**Comment by swails** [comment]
> We can add the 10-12 potential as a CustomNonbondedForce.

I know we can ([that's what `AmberParm` does](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/_amberparm.py#L996-L1021) when it's present).

> How is that represented in AmberParameterSet?

[It's not](https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/parameters.py#L494-L496), and I have no plans to add it.  That term hasn't been used in decades with no plans to add it back.  If users *must* have it in OpenMM, they can parametrize through LEaP and I think that's good enough.  You'll never convince @peastman or Vijay that FF91 or anything older is worth bundling :)

**Comment by swails** [comment]
OK, this is ready to go.  Let me know if anything looks weird or doesn't quite work for your needs.

**Comment by rafwiewiora** [comment]
> OK, the only thing left to do here is expose lib/oldff if this is actually needed. But is it? There's nothing I see in that folder that would be worth using as far as I can tell. The newest thing there is ff91

Not quite, from leaprc.ff02 (and that's an FF that's even listed in the 'main' table of forcefields to use in LEaP on page 31 of the newest manual):
```
loadOff all_nucleic02.lib
loadOff all_amino02.lib
loadOff all_aminoct02.lib
loadOff all_aminont02.lib
```

And those files are in lib/oldff - my money is on someone made a mistake copying? I see no reason to have ff02 files and oldff and ff99 files not in oldff....

**Comment by rafwiewiora** [comment]
Sorry, I commented on a parm/oldff line in one of your commits wrongly rather then in the PR (saying I didn't see that directory), but now I see here you've commented it out! (I deleted that comment, just saying in case you have a weird notification not pointing anywhere existing...)

**Comment by rafwiewiora** [comment]
> OK, this is ready to go. Let me know if anything looks weird or doesn't quite work for your needs.

I guess you've tested against all the cases that were causing problems that I reported? Then no further testing / needs I can do!

**Comment by swails** [comment]
That's an old polarizable FF.  Admittedly newer than 91, but ParmEd doesn't know how to handle polarizable FFs (except some limited AMOEBA support).  There's still nothing in `lib/oldff` that ParmEd currently supports *or* that we'd want to distribute with OpenMM.  Nobody in Amber currently uses it to my knowledge.

I *did* add a `search_oldff` argument in the `from_leaprc` constructor, but you should never set it to `True` in any of your conversions.

**Comment by rafwiewiora** [comment]
> That's an old polarizable FF. Admittedly newer than 91, but ParmEd doesn't know how to handle polarizable FFs (except some limited AMOEBA support).

Oh I see!

> I did add a search_oldff argument in the from_leaprc constructor, but you should never set it to True in any of your conversions.

Alright, that's good to have just in case.

**Comment by swails** [comment]
The parm91Xua.dat or whatever file (with angle definitions using only 2 atom types) weren't tested (nor was supported added).  But everything else in #593 was addressed (lipid11.lib was not explicitly tested, but lipid14.lib is now part of the test suite).

Still doesn't support loadMol2, but I have to adjust the leaprc processing a little bit to support that (since in that case, order of loadOFF and loadMol2 files matter).  I'll go ahead and merge this and add the loadMol2 command support as a separate feature enhancement request.

**Pull request merged**
