### PR TITLE
 add tests for boxes

### PR DESCRIPTION
**Pull request by hainm**
- add tests for boxes
- fix doc

### CODE REVIEW

**Comment by hainm** [comment]
should update https://github.com/ParmEd/ParmEd/pull/674 (after merging) to this PR

**Comment by hainm** [comment]
just merge upstream.

**Comment by swails** [comment]
The only failure of any substance here is the pypy one. You need to protect your new test from running under pypy because NetCDF doesn't work there yet. 

There are plenty of examples where this is done in the test suite.

**Comment by hainm** [comment]
Ok I will update tonight.

**Comment by swails** [comment]
Other than that tiny comment, this looks great.  Thanks!

**Comment by hainm** [comment]
here we go.

**Comment by swails** [comment]
Thanks!

**Pull request merged**
