### PR TITLE
correctly parsing space group for cif file.

### PR DESCRIPTION
**Pull request by hainm**

### CODE REVIEW

**Comment by hainm** [comment]
good for review now.

**Comment by swails** [comment]
Thanks!

**Comment by hainm** [comment]
can you pull to amber git if you have a chance. thanks.

**Comment by hainm** [comment]
just to be clear `amber git` is the one in `git.ambermd.org`. We want to test with phenix code.

**Comment by swails** [comment]
Yea, I know.  I did it this morning, I just forgot to push.  Should be done now.

**Comment by hainm** [comment]
thanks. Just see your commits.

**Pull request merged**
