### PR TITLE
coverage on coveralls.io

### PR DESCRIPTION
**Pull request by hainm**
look better with color. 

demo from [pytraj] (https://coveralls.io/builds/4337398/source?filename=%2Fhome%2Ftravis%2Fminiconda%2Fenvs%2Fmyenv%2Flib%2Fpython2.7%2Fsite-packages%2Fpytraj%2Fcommon_actions.py)

Will update parmed demo later when this PR passes.

### CODE REVIEW

**Comment by hainm** [comment]
demo report for [parmed] (https://coveralls.io/builds/4337588/source?filename=%2Fhome%2Ftravis%2Fminiconda%2Fenvs%2Fmyenv%2Flib%2Fpython3.3%2Fsite-packages%2Fparmed%2Fstructure.py)

**Comment by swails** [comment]
I think it's time to streamline the tests a bit.  Adding coverage bumps the time up to ~40 minutes for the test suite, which is too long.  This is nice, though, and I'd like to incorporate it!

**Comment by swails** [comment]
OK!  I profiled the test suite and made a few small changes that cut the runtime of the tests almost in half.  We should be able to go ahead and add coverage to the test suite now.  This PR has quite a few conflicts at this point.  Options here:

- You can merge master and resolve conflicts
- Just open a new PR (you or me?)

Since I want to test error detection and handling, the only lines I really want to omit from the coverage report are `assert` statements.  I also don't really want to report on the coverage of 3rd-party modules, so we need to omit the subpackages `parmed/utils/six.py`, `parmed/utils/fortranformat`, and `parmed/formats/pdbx`.

What do you want to do here?  Do you want me to just pull some of the stuff you did in this PR and open a new one?

**Comment by hainm** [comment]
Yeah, go ahead to make your PR.

Hai

**Pull request closed without merging**
