### PR TITLE
Hacky workaround for conda Python on macs.

### LINKED ISSUE #1024: fatal error: 'locale' file not found (MacOS Mojave)
Hi,

any idea how to fix that issue with MacOS Mojave. The install is quite simple.

```
pip install parmed
```

```
    /private/var/folders/q9/y2dwpbb13ydclj2mr6btq3xw0000gn/T/pip-install-u47ydriv/parmed/src/readparm.h:5:10: fatal error: 'locale' file not found
    #include <locale>
             ^~~~~~~~
    1 warning and 1 error generated.
    error: command 'clang' failed with exit status 1
```

### PR DESCRIPTION
**Pull request by swails**
Fixes #1024 

fix

### CODE REVIEW

**Comment by mattwthompson** [comment]
This works for me locally (with a lot of warnings, as I'm sure is expected).

**Comment by swails** [comment]
What warnings?

**Comment by mattwthompson** [comment]
https://gist.github.com/mattwthompson/eda03ae276cee8ad9fd648c630c4084a

I don't know C well enough to know how alarming this is, but it builds/tests/runs fine. My environment and compilers can sometimes be slightly wonky, so this could also just be on my end ...

**Comment by swails** [comment]
I don’t see any of those warnings. They’re all warnings from the stdlib or Python.h as well, which is even stranger. 

I’m not sure what is different about your environment than mine, but if the optimized parser works I think you’re fine.

**Comment by mattwthompson** [comment]
All good here (well, kinda strange, but plenty workable). Just wanted to report my results in addition to yours and CI

**Comment by hainm** [comment]
@swails  can you please make a PR to gitlab? thanks.

**Pull request merged**
