### PR TITLE
reading gromacs topologies with insertion codes fixed

### PR DESCRIPTION
**Pull request by Valdes-Tresanco-MS**
I fix issue #1153. I tested it and it works correctly. In addition, it does not imply severe modifications that must be extensively tested. I hope it helps

Mario S.

### CODE REVIEW

**Comment by Valdes-Tresanco-MS** [comment]
This PR is based on the master branch, so I closed and open a new one based on the v3.4 branch

**Comment by swails** [comment]
I'd like to get it in master also.

**Comment by Valdes-Tresanco-MS** [comment]
I closed the PR because I got an error with mdin.py in the master branch. Comparing both branches, the master and v3.4, I saw that there are notable differences. Although this PR has nothing to do with it.

**Comment by swails** [comment]
Thanks!

**Pull request merged**
