### PR TITLE
Add ParmEd to Python CMake component

### PR DESCRIPTION
**Pull request by multiplemonomials**
This is a small change to put ParmEd into the "python" sub-package.

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by multiplemonomials** [comment]
run jenkins

**Comment by multiplemonomials** [comment]
oh well I wanted to at least see if that would work

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
@multiplemonomials -- I've added you to the whitelist so your commits (and run-jenkins comments) will trigger builds on ParmEd now.

**Comment by multiplemonomials** [comment]
run jenkins

**Comment by multiplemonomials** [comment]
Awesome, thanks.

**Pull request merged**
