### PR TITLE
bugfix, inlude END in section

### PR DESCRIPTION
**Pull request by ChayaSt**
This fixes issue https://github.com/ParmEd/ParmEd/issues/600

### CODE REVIEW

**Comment by swails** [comment]
Have you seen the Travis failures?  Any idea what may be causing it?

**Comment by ChayaSt** [comment]
I'll take a look at it.

**Comment by ChayaSt** [comment]
So adding the 'END' line to the section is causing all these errors to be raised because it is assumed that there is no 'END' in the section. I can add some if statements to get rid of these errors make sure that it doesn't get processed.

**Comment by swails** [comment]
Is this good to go?

**Comment by ChayaSt** [comment]
All tests passed so I think it's good to go.

**Comment by swails** [comment]
Merged, thanks!

**Pull request merged**
