### PR TITLE
Bugfix/do not sort charmm impropers

### PR DESCRIPTION
**Pull request by swails**
Fixes #915

### CODE REVIEW

**Comment by jvermaas** [comment]
This definitely fixes my issue. I just needed a non-dictionary sort. It also looks much cleaner now. :+1:

**Comment by swails** [comment]
It's still failing a lot of the tests because it can't find the improper torsion parameters... :(.  Blech.

**Comment by swails** [comment]
And see this is why I did things the way I did originally.  I followed the rules they laid out in their documentation, but I still get missing parameters on systems I *know* CHARMM works on.

So whatever ruleset they use for assigning improper parameters within CHARMM isn't actually documented *correctly* anywhere I can find it.

**Comment by jvermaas** [comment]
Which check is actually failing? In going through the test cases, I couldn't find one that actually loaded parameter sets in a useful way so that I could recapitulate the failure and use my typical "print" debugging techniques. The way it was done originally was flat out wrong for merging together parameter files, since it would change the physics encoded in the parameter file when written out again.

**Pull request merged**
