### PR TITLE
change overload to override in the ffxml tag

### PR DESCRIPTION
**Pull request by rafwiewiora**
Small change here, due to analogical change in OpenMM (https://github.com/pandegroup/openmm/commit/6ce433934296d05dfb08557c98746c073373d67b , also see https://github.com/choderalab/openmm/issues/17). 

Should I also change the `residue.overload_level` to be `residue.override_level` ?

### CODE REVIEW

**Comment by swails** [comment]
> Should I also change the residue.overload_level to be residue.override_level ?

Yes.  You guys are the only one using this tag at the moment, and Peter's justification for override echoes my thoughts.

**Comment by rafwiewiora** [comment]
Alright, this should be all ready!

**Comment by swails** [comment]
It says there are conflicts that need to be resolved.  Can you merge master and resolve the conflicts first?

**Comment by rafwiewiora** [comment]
Ok, I've given up on the mess that I seem to have in the repo, opening a new PR from a new branch.

**Pull request closed without merging**
