### PR TITLE
Mass should be case-insensitive

### PR DESCRIPTION
**Pull request by ChayaSt**
I ran into a CharMM stream file where MASS is written as Mass. 
Here's the file:
https://github.com/ChayaSt/Charmm36_FF/blob/master/toppar/stream/misc/toppar_ions_won.str#L31-L95

### CODE REVIEW

**Comment by swails** [comment]
Is this just true for MASS, or will the other sections need similar modifications?

**Comment by ChayaSt** [comment]
I went through all the files and haven't found a different section that needs this modifications. However, I was wondering if we should just make all section titles case-insensitive? Since the files are obviously not consistent.

**Comment by ChayaSt** [comment]
There is another issue I came across.

When you load many files in ```CharmmParameterSet```, you should be able to look up the patches in the   patches dict that's bound to the class if the patches were read in a different file. However, the way the code works now is that ```read_topology_file```  creates a new dict patches internal to the function and some patches are not found. I can change that too.

**Comment by swails** [comment]
I think CHARMM conventions is to ignore case. So let's make all section IDs case insensitive.

I'm not sure that I see the difference in your patch handling and what was there before, but yours is arguably the better way to do things anyway.

**Comment by swails** [comment]
Excellent!  This looks like it's good to go, yes?

**Comment by ChayaSt** [comment]
Yes.

**Comment by swails** [comment]
Excellent.  In it goes.

**Pull request merged**
