### PR TITLE
Implement improved processing of parm.dat files when equivalence lines LIE

### PR DESCRIPTION
**Pull request by swails**
See the discussion in choderalab/openmm#7.  This commit should fix that issue.

### CODE REVIEW

**Comment by rafwiewiora** [comment]
Thank you sir! Would it be possible to make the warning a different Warning sub-class though? I must filter ParameterWarnings like this: https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L171 to an error in the conversion script, so I'm going to have to start filtering by warning message too if this is a ParameterWarning also...

**Comment by swails** [comment]
How about `AmberWarning`, since this is technically an issue with AMBER files?

**Comment by rafwiewiora** [comment]
Sounds great!

**Comment by rafwiewiora** [comment]
Confirmed this solves the issue with AM1 / PM3, updated my script already.

**Comment by swails** [comment]
Done.  I'll merge when this is done.

**Comment by swails** [comment]
"this is done" == Travis passes :smiley:

**Comment by rafwiewiora** [comment]
:+1:

**Comment by swails** [comment]
Good to go!

**Comment by rafwiewiora** [comment]
Thanks! BTW how often does the dev conda package get rebuild? I've been installing from the repo so far just in case.

**Comment by swails** [comment]
> Thanks! BTW how often does the dev conda package get rebuilt? I've been installing from the repo so far just in case.

Not sure.  I don't really keep on top of updating the conda package.  I usually use pip, which can install straight from a git repo.

**Comment by rafwiewiora** [comment]
Ah okay. @jchodera something to note here for you, because you're conda installing parmed-dev in the Travis testing for the conversion.

**Comment by hainm** [comment]
@swails may be you should update pip install from github in README too, so user just need to copy and paste.

**Comment by jchodera** [comment]
> Not sure. I don't really keep on top of updating the conda package. I usually use pip, which can install straight from a git repo.

`parmed-dev` packages are rebuilt nightly:
https://github.com/omnia-md/conda-dev-recipes

**Comment by swails** [comment]
Good to know

**Comment by rafwiewiora** [comment]
:+1:

**Pull request merged**
