### PR TITLE
Add warning when replacing residues

### PR DESCRIPTION
**Pull request by ChayaSt**
Turns out CharMM has many duplicate residues with different atom types across different force fields that should be compatible. I didn't check yet if the parameters are identical for these atom types, but I thought it's good to get a warning when they get overwritten. I still need to figure out how to handle this. If the parameters are all identical, it shouldn't matter. But if they're not, we might need to write out both and use  overload.

### CODE REVIEW

**Comment by ChayaSt** [comment]
In that line I am checking if the residue that is being parsed in the current file already exists in ```CharmmParameterSet```

**Comment by hainm** [comment]
@jswails: what's about turn off coverage report un PR? Kind of distracting.

**Comment by swails** [comment]
The failure here is fake.  Is this still needed?  And if so, good to merge?

**Comment by hainm** [comment]
@ChayaSt 

```python
if resname in self.residues:
```
I am kind of confused. Is `resname` string and self.residues ResidueList? if yes for both, this is somewhat dangerous.

**Comment by swails** [comment]
`self.residues` is a dict matching a string with either a `ResidueTemplate` or `ResidueTemplateContainer`.

**Comment by hainm** [comment]
I see.

**Comment by ChayaSt** [comment]
> Is this still needed? And if so, good to merge?

Yes.

**Pull request merged**
