### PR TITLE
Fix bug where OpenMM ffxml files did not contain AMBER disulfide bonds (and other external connections)

### LINKED ISSUE #964: Handling disulfide bond definitions in AMBER
We seem to have run into an issue where AMBER `CYX` residue templates are missing the `<ExternalBond>` tag for `SG`.  See https://github.com/pandegroup/openmm/issues/2003

It looks like disulfide bonded atoms are stored in [`ResidueTemplate.connections`](https://github.com/ParmEd/ParmEd/blob/master/parmed/modeller/residue.py#L88), but these are not written out in [`_write_omm_residues()`](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L290).

I'll take a stab at fixing this.

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #964:
- [x] `ResidueTemplate.connections` is now written as `<ExternalBond>` tags in `_write_omm_residues()`
- [x] Test added to ensure that protein with disulfide bonds is correctly parameterized

@swails: This should be ready to review and merge, but when I ran the tests locally with `$AMBERHOME` set, I noticed some other tests I hadn't touched were failing, and have probably been failing for some time:
```
Test correct support for the override_level attribute of ResidueTemplates and correct writing to XML tag ... ERROR
Test writing XML parameters loaded from Amber files ... ok
Test the write_unused argument in writing XML files ... FAIL
Test writing XML parameters loaded from Amber GAFF parameter files ... ok
Test writing small XML modifications ... ok

======================================================================
ERROR: Test that no identical residues are written to XML, using the templhasher function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/github/parmed/ParmEd.jchodera/test/test_parmed_openmm.py", line 586, in test_not_write_residues_with_same_templhash
    new_residues[name] = params.residues[name]
KeyError: 'K'

======================================================================
ERROR: Test correct support for the override_level attribute of ResidueTemplates and correct writing to XML tag
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/github/parmed/ParmEd.jchodera/test/test_parmed_openmm.py", line 599, in test_override_level
    new_residues['K'] = params.residues['K']
KeyError: 'K'

======================================================================
FAIL: Test the write_unused argument in writing XML files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/github/parmed/ParmEd.jchodera/test/test_parmed_openmm.py", line 544, in test_write_xml_parameters_amber_write_unused
    self.assertEqual(len(ffxml.readlines()), 2178)
AssertionError: 2179 != 2178
-------------------- >> begin captured logging << --------------------
parmed.openmm.parameters: DEBUG: Valid patch combinations:
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 6 tests in 2.394s

FAILED (errors=2, failures=1)
```
I'm not quite sure what to do about those.

### CODE REVIEW

**Comment by swails** [comment]
Can you include a smaller PDB file? This one looks huge for a disulfide bond test

**Comment by jchodera** [comment]
850K? What if we gzip it?

I don't have any smaller PDBs that have been appropriately prepared. This was the actual discovered failure case, so it seemed wisest (and most convenient) to test that to make sure the bug was fixed.

**Comment by jchodera** [comment]
Are you sure you're not misreading this? Here's the list of files just in `test/files/` that are bigger than that:
```
-rw-r--r--   1 choderaj  9696963   883K Oct  7 11:16 solv2.parm7
-rw-r--r--   1 choderaj  9696963   897K Oct  7 11:16 cyclohexane.parm7
-rw-r--r--   1 choderaj  9696963   960K Oct  7 11:16 complex.prmtop
-rw-r--r--   1 choderaj  9696963   994K Oct  7 11:16 4lzt.les.parm7
-rw-r--r--   1 choderaj  9696963   1.1M Oct  7 11:16 nma.parm7
-rw-r--r--   1 choderaj  9696963   1.2M Oct  7 11:16 top_all36_cgenff.rtf
-rw-r--r--   1 choderaj  9696963   1.4M Oct  7 11:16 tz2.truncoct.crd
-rw-r--r--   1 choderaj  9696963   1.5M Oct  7 11:16 different_molecules.parm7
-rw-r--r--   1 choderaj  9696963   1.5M Oct  7 11:40 state_974wat.xml
-rw-r--r--   1 choderaj  9696963   2.0M Oct  7 11:16 dhfr_cmap_pbc.rst7
-rw-r--r--   1 choderaj  9696963   2.1M Oct  7 11:16 solv.rst7
-rw-r--r--   1 choderaj  9696963   2.4M Oct  7 11:16 solvents.lib
-rw-r--r--   1 choderaj  9696963   2.7M Oct  7 11:16 Mg_ti1_b.parm7
-rw-r--r--   1 choderaj  9696963   3.5M Oct  7 11:16 benzene_cyclohexane_10_500.prmtop
-rw-r--r--   1 choderaj  9696963   4.3M Oct  7 11:16 4lzt.parm7
-rw-r--r--   1 choderaj  9696963   4.9M Oct  7 11:16 solv.prmtop
-rw-r--r--   1 choderaj  9696963   7.5M Oct  7 11:16 dhfr_min_charmm.crd
-rw-r--r--   1 choderaj  9696963   8.3M Oct  7 11:16 4lyt_vmd.pdb
-rw-r--r--   1 choderaj  9696963   8.4M Oct  7 11:16 overflow.pdb
-rw-r--r--   1 choderaj  9696963   8.5M Oct  7 11:16 1ffk.cif
-rw-r--r--   1 choderaj  9696963   9.1M Oct  7 11:16 4TVP-dmj_wat-ion.psf
-rw-r--r--   1 choderaj  9696963   9.7M Oct  7 11:16 dhfr_cmap_pbc.parm7
-rw-r--r--   1 choderaj  9696963    10M Oct  7 11:16 dhfr_cmap_pbc.psf
-rw-r--r--   1 choderaj  9696963    12M Oct  7 11:16 amoeba.parm7
-rw-r--r--   1 choderaj  9696963    16M Oct  7 11:16 system_974wat.xml
-rw-r--r--   1 choderaj  9696963    20M Oct  7 11:16 jac.analout
```
I'm not sure it makes any sense to worry about the size of the 30th largest file in that directory when you have individual files 23x bigger.

**Comment by jchodera** [comment]
Also, we can reuse this file for some other reasonable protein tests. It's currently actually testing that all the amino acids in a protein can be correctly assigned via `app.ForceField`, which I should really have included earlier! And later on, we can include comparison between CHARMM and AMBER energies for this file too, which will help with additional test coverage.

**Comment by swails** [comment]
There are way too many large files in the test suite :). Gzipping won’t do any good — fit already compresses the content in clones and pulls. 

If I had refactoring time, I’d refactor a lot of the long methods and break out the unit tests from the integration ones. And the unit tests should really be small and isolated (which mine aren’t).

**Comment by swails** [comment]
But I guess it’s fine. I don’t have the time to fix what I want to fix. 

I’ll look into the other failures when I get a chance.

**Comment by jchodera** [comment]
> But I guess it’s fine. I don’t have the time to fix what I want to fix.

That's what Google Summer of Code is for!

Have you thought of pitching ParmEd as a GSoC cheminformatics project?

https://www.openchemistry.org/gsoc/

**Pull request merged**
