### PR TITLE
Ack.  Update version numbers.  I need a better way of doing this.

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
I have used `versioneer` for a couple of new repos, and it's kind of clever, but it didn't seem worth it to retrofit already estabilished projects. https://github.com/warner/python-versioneer

**Comment by hainm** [comment]
for only 2 numbers needed to change, I prefer to manually update.

**Comment by swails** [comment]
Man, I wish I knew about versioneer earlier.  Changing it by hand is fine... as long as I remember to do it.  I personally like the idea of pulling version info from the commit hash for between-release developmental versions.  @rmcgibbo -- is versioneer easy to use?

**Comment by rmcgibbo** [comment]
Yeah, it's straightforward. Very convention-over-configuration.

**Pull request merged**
