### PR TITLE
Mol2 fix?

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
```
wget https://raw.githubusercontent.com/choderalab/openmoltools/master/openmoltools/chemicals/etoh/etoh.mol2

pylab
import chemistry
struct = chemistry.load_file("./etoh.mol2")
chemistry.formats.Mol2File.write(struct, "./etoh2.mol2")

tleap
source leaprc.gaff
etoh2 = loadmol2 etoh2.mol2


tleap
source leaprc.gaff
etoh2 = loadmol2 etoh.mol2

> etoh2 = loadmol2 etoh2.mol2
Loading Mol2 file: ./etoh2.mol2
Reading MOLECULE named LIG
> 

> etoh2 = loadmol2 etoh.mol2
Loading Mol2 file: ./etoh.mol2
Reading MOLECULE named LIG

```

**Comment by swails** [comment]
+1.  When Travis passes I'll merge it in.  Thanks for the fix.

I'll tidy up the formatting shortly.

**Comment by swails** [comment]
The failure is because there's a difference between giving `Mol2File.write` a `ResidueTemplate` instance and a `Structure` instance.

For a multi-residue mol2 file, how should we name the unit?  I'm tempted to just use the residue name of the first residue -- the name isn't actually *used* for anything inside Amber (not sure about other packages).

**Comment by kyleabeauchamp** [comment]
So we have a multi-molecule mol2 here: https://github.com/choderalab/openmoltools/blob/master/openmoltools/chemicals/drugs/Zdd.mol2.gz

Looks like the following:

```
@<TRIPOS>MOLECULE
ZINC03873936
   68    72     0     0     0
SMALL
USER_CHARGES
1-[4-[[2-(2,4-dichlorophenyl)-2-(1,2,4-triazol-1-ylmethyl)-1,3-dioxolan-4-yl]methoxy]phenyl]-4-isopropyl-piperazine
@<TRIPOS>ATOM

[...]

@<TRIPOS>MOLECULE
ZINC03817234
   79    83     0     0     0
SMALL
USER_CHARGES
```

**Comment by kyleabeauchamp** [comment]
I have no strong preference on what to do here.

**Comment by swails** [comment]
Oh man.  Where did you get that mol2 file?  I had no idea multiple residues were specified that way (i.e., each with its own sections)...

**Comment by kyleabeauchamp** [comment]
I believe it's the zinc drug database?  Here is an example using OpenEye to parse it:

https://github.com/choderalab/openmoltools/blob/master/openmoltools/tests/test_drugs.py

**Comment by swails** [comment]
OK.  Then I'll update the mol2 parser to support these files.

**Comment by kyleabeauchamp** [comment]
The Zdd file is probably low priority, I'm quite OK punting on that one.

**Comment by swails** [comment]
OK.  Should I just merge this and fix up the other issues in another PR?

**Comment by hainm** [comment]
@kyleabeauchamp  @swails 

for multiple molecules in a single mol2 file, what I am expecting when using
```python
struct = chemistry.load_file("./Zdd.mol2")

**Comment by swails** [comment]
By default, Mol2 and Mol3 files are parsed as a `ResidueTemplate` (kind of a cross between a `Residue` and a `Structure`, but it only contains bonds and atoms, but also a HEAD and TAIL identifier that says where and how it connects to adjacent residues in a sequence).  If it defines multiple residues, it parses to a `ResidueTemplateContainer` (which is basically just a list of `ResidueTemplate` instances).

You can pass the `structure=True` keyword to the `load_file` (or `Mol2File.parse` function) to have it return a `Structure` instead.

**Comment by kyleabeauchamp** [comment]
Sure, works for me

**Pull request merged**
