### PR TITLE
OSX

### PR DESCRIPTION
**Pull request by hainm**
adding OSX to travis build

on .travis.yml, I remove 'language = python' to 'generic' so travis does not check python from begining (we use miniconda).

I also remove 'md5sum' check since I am not sure if this is helpful.

This PR does not pass the tests yet (#431 ). Consider this is my proposal. If you would like to add osx, you still need to do further.

### CODE REVIEW

**Comment by swails** [comment]
+1.

Do you know if it's possible to trim the matrix down at all, so that maybe only one version of Python is tested for OS X?  With 6 entries in the build matrix, only 5 can run at once with a free account so it'll take twice as long to finish the tests as it currently does.

**Comment by hainm** [comment]
yeah, I think we could do that. Let me update PR.

**Comment by hainm** [comment]
@swails 

I am done: only 4 jobs on travis now.

https://travis-ci.org/hainm/ParmEd/builds/81411715

It's likely that you need to update gromacs-related stuff too.

**Comment by swails** [comment]
I just submitted a PR into your branch that should fix the Travis errors.

**Comment by swails** [comment]
Can you merge master into this branch again and see if it fixes Travis?

**Comment by hainm** [comment]
okie

**Comment by hainm** [comment]
finally done.

**Comment by swails** [comment]
Looks good.  Thanks!

**Pull request merged**
