### PR TITLE
Screw this, I'm moving to Canada.

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by hainm** [comment]
:( I am thinking about that too. Canada website for immigrant broken yesterday night. :))

**Comment by swails** [comment]
I'm just... sad. So sad. And ashamed of the much larger basket of deplorables all around us. 

--
Jason M. Swails

**Comment by hainm** [comment]
ha, brexit and trumpkin.

**Comment by mrshirts** [comment]
Stay!  We need everybody to help.

**Comment by mrshirts** [comment]
We all need to talk to each other to figure out what everyone else is
thinking.  Because clearly most of America doesn't know what other people
in America are thinking.

**Comment by swails** [comment]
Just to clarify, the title here was meant as a joke -- I'm == ParmEd in the title here.  *I* have no intention of moving to Canada :)

**Comment by ctk3b** [comment]
He's back!

**Pull request closed without merging**
