### PR TITLE
Implement CHARMM file writing support

### LINKED ISSUE #305: Write CHARMM parameter files and PSFs
This would officially allow ParmEd to interoperate between Amber, Gromacs, and CHARMM (leaving only a few programs completely unsupported, like LAMMPS).

What needs to be done for this:

- [x] `CharmmParameterSet.from_parameterset` to automatically convert atom type names into upper-case and ensure type name uniqueness
- [x] `CharmmParameterSet.write` to write a parameter file (probably just a stream file)
- [x] ~~IC table processing (? probably doesn't need to be done for this feature) in the residue templates~~
- [x] `CharmmPsfFile.from_structure` to augment the bond, angle, and torsion list from the bond graph to make sure the exclusions and exceptions are correct (same as is done for `AmberParm`), and do the type naming changes described above for `CharmmParameterSet`
- [ ] validate

EDIT 1:
- [x] `CharmmParameterSet.from_structure` should behave correctly

### PR DESCRIPTION
**Pull request by swails**
Closes #305

### CODE REVIEW

**Comment by swails** [comment]
This isn't completely finished yet.  I still need to fix the handling of improper types (this has been a long time coming).

Right now ParmEd cheats by putting everything in alphabetical order and matching impropers based on that.  But this loses the order that becomes necessary when we want to write out these files... sigh.

**Comment by swails** [comment]
OK, CHARMM parameter files are really irritating here.  This is a quote from [the main CHARMM documentation on parameter files](http://www.charmm.org/documentation/c32b2/parmfile.html):

> Improper dihedrals (E) IMPH, used for out of plane motions are specified in the same fashion as dihedrals.  The use of wildcards, X, is also allowed in a number of variations.  Multiple improper
dihedrals are not supported.  By convention, the first atom of an improper dihedral (type A-X-X-B or A-B-C-D) is usually the central atom.  This had been a general rule in the past.

 This is a segment from the `par_all36_prot.prm` file:

```
IMPROPER
!
!V(improper) = Kpsi(psi - psi0)**2
!
!Kpsi: kcal/mole/rad**2
!psi0: degrees
!note that the second column of numbers (0) is ignored
!
!atom types           Kpsi                   psi0
!
HE2  HE2  CE2  CE2     3.0            0      0.00   ! 
		! for ethene, yin/adm jr., 12/95
HR1  NR1  NR2  CPH2    0.5000         0      0.0000 ! ALLOW ARO
                ! his, adm jr., 7/05/90
HR1  NR2  NR1  CPH2    0.5000         0      0.0000 ! ALLOW ARO
                ! his, adm jr., 7/05/90
HR3  CPH1 NR1  CPH1    0.5000         0      0.0000 ! ALLOW ARO
                ! adm jr., 3/24/92, maintain old aliphatic H VDW params
HR3  CPH1 NR2  CPH1    0.5000         0      0.0000 ! ALLOW ARO
                ! adm jr., 3/24/92, maintain old aliphatic H VDW params
HR3  CPH1 NR3  CPH1    1.0000         0      0.0000 ! ALLOW ARO
                ! adm jr., 3/24/92, maintain old aliphatic H VDW params
HR3  NR1  CPH1 CPH1    0.5000         0      0.0000 ! ALLOW ARO
                ! adm jr., 3/24/92, maintain old aliphatic H VDW params
HR3  NR2  CPH1 CPH1    0.5000         0      0.0000 ! ALLOW ARO
                ! adm jr., 3/24/92, maintain old aliphatic H VDW params
N    C    CP1  CP3     0.0000         0      0.0000 ! ALLOW PRO
```

This *clearly* violates the documentation (or the term "usually" is applied very liberally).  It does seem that in some instances, the central atom type is listed first.  Other times, it's listed second.  Still other times it's listed third.  And there's no way to *know* this without a lot of gymnastics (i.e., looking at the residue templates and matching it up with the listed impropers), and even that won't hit all of the terms defined here.

The only style that actually seems consistent in CHARMM parameter files is that wild-cards always take the last three or middle two spots.  So I updated the parameter file writer to do this when applicable (although when generating from a `Structure`, there are never wild-cards).

The best I can do is hope that CHARMM doesn't care about the order of atom types in the `IMPROPER` records when assigning them (and based on the haphazard order in the official parameter files, I don't see how CHARMM could possibly care).

@davidlmobley -- this should be ready to test.  If it's easier for Doug to test this if I merge it into master, I can certainly do that (but I'd rather wait on it until it's validated if it made no difference to him).

**Comment by davidlmobley** [comment]
@jswails - Sunhwan Jo has agreed to help with testing here so I've passed
this on to him.

Thanks.

On Wed, Jul 29, 2015 at 10:32 AM, Jason Swails <notifications@github.com>
wrote:

> OK, CHARMM parameter files are really irritating here. This is a quote
> from the main CHARMM documentation on parameter files
> <http://www.charmm.org/documentation/c32b2/parmfile.html>:
>
> Improper dihedrals (E) IMPH, used for out of plane motions are specified
> in the same fashion as dihedrals. The use of wildcards, X, is also allowed
> in a number of variations. Multiple improper
> dihedrals are not supported. By convention, the first atom of an improper
> dihedral (type A-X-X-B or A-B-C-D) is usually the central atom. This had
> been a general rule in the past.
>
> This is a segment from the par_all36_prot.prm file:
>
> IMPROPER
> !
> !V(improper) = Kpsi(psi - psi0)**2
> !
> !Kpsi: kcal/mole/rad**2
> !psi0: degrees
> !note that the second column of numbers (0) is ignored
> !
> !atom types           Kpsi                   psi0
> !
> HE2  HE2  CE2  CE2     3.0            0      0.00   !
>         ! for ethene, yin/adm jr., 12/95
> HR1  NR1  NR2  CPH2    0.5000         0      0.0000 ! ALLOW ARO
>                 ! his, adm jr., 7/05/90
> HR1  NR2  NR1  CPH2    0.5000         0      0.0000 ! ALLOW ARO
>                 ! his, adm jr., 7/05/90
> HR3  CPH1 NR1  CPH1    0.5000         0      0.0000 ! ALLOW ARO
>                 ! adm jr., 3/24/92, maintain old aliphatic H VDW params
> HR3  CPH1 NR2  CPH1    0.5000         0      0.0000 ! ALLOW ARO
>                 ! adm jr., 3/24/92, maintain old aliphatic H VDW params
> HR3  CPH1 NR3  CPH1    1.0000         0      0.0000 ! ALLOW ARO
>                 ! adm jr., 3/24/92, maintain old aliphatic H VDW params
> HR3  NR1  CPH1 CPH1    0.5000         0      0.0000 ! ALLOW ARO
>                 ! adm jr., 3/24/92, maintain old aliphatic H VDW params
> HR3  NR2  CPH1 CPH1    0.5000         0      0.0000 ! ALLOW ARO
>                 ! adm jr., 3/24/92, maintain old aliphatic H VDW params
> N    C    CP1  CP3     0.0000         0      0.0000 ! ALLOW PRO
>
> This *clearly* violates the documentation (or the term "usually" is
> applied very liberally). It does seem that in some instances, the central
> atom type is listed first. Other times, it's listed second. Still other
> times it's listed third. And there's no way to *know* this without a lot
> of gymnastics (i.e., looking at the residue templates and matching it up
> with the listed impropers), and even that won't hit all of the terms
> defined here.
>
> The only style that actually seems consistent in CHARMM parameter files is
> that wild-cards always take the last three or middle two spots. So I
> updated the parameter file writer to do this when applicable (although when
> generating from a Structure, there are never wild-cards).
>
> The best I can do is hope that CHARMM doesn't care about the order of atom
> types in the IMPROPER records when assigning them (and based on the
> haphazard order in the official parameter files, I don't see how CHARMM
> could possibly care).
>
> @davidlmobley <https://github.com/davidlmobley> -- this should be ready
> to test. If it's easier for Doug to test this if I merge it into master, I
> can certainly do that (but I'd rather wait on it until it's validated if it
> made no difference to him).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/pull/307#issuecomment-126029633>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by swails** [comment]
Ha!  There *is* a (new) jswails user on Github... sorry for the accidental ping.

> Sunhwan Jo has agreed to help with testing here so I've passed
> this on to him.

Sounds great.  If there's anything I can do to help, please let me know.

**Comment by hainm** [comment]
@real_jswails_here: you really need to solve the openmm problem on travis. Kind of annoying to merge when the build is fail (all the times).

**Comment by swails** [comment]
I think it's a *very* subtle bug in the OpenMM CPU platform.  Unfortunately, it's not a rare race condition (which would've been solvable by using a single thread), but I've been wholly unable to reproduce it anywhere else.

It could either be:

1. A bug in Docker/Travis's infrastructure.
2. A bug in OpenMM's CPU platform

As I said, I'm inclined to think the latter, but I honestly don't know how to go about debugging this (let alone fixing it).

**Comment by sunhwan** [comment]
@swails Hi Jason, can you show me a simple example on how to convert prmtop to charmm using your code? I'll try to test if the conversion is correctly done by comparing the energies.

**Comment by swails** [comment]
Sure -- the following should work:

```Python
import parmed as pmd

# start from an Amber topology and coordinate file
parm = pmd.load_file('something.parm7', 'something.rst7')

# Convert to a PSF file
psf = pmd.charmm.CharmmPsfFile.from_structure(parm)
params = pmd.charmm.CharmmParameterSet.from_structure(psf)

# Write the files
psf.save('something.psf') # Write the PSF file
psf.save('something.crd') # Write the CHARMM coordinate file

# Now write the parameters, either as a RTF/PRM pair or as a single stream file
params.write(top='params.rtf', par='params.prm')
# ... or ...
params.write(str='params.str')
```

As soon as I started typing up this example, I remembered that I never actually added support for writing CHARMM coordinate files :).  I just went ahead and added support for that just now with some unit tests.  So if you get some error messages about `.crd` not being a recognized extension, please make sure you pull the latest code from this branch.  Obviously you need to replace the strings with the filenames corresponding to your test.

Thanks!

**Comment by sunhwan** [comment]
@swails I tried to generate rtf/prm from benzene_cyclohexzne_50_100.prmtop file in the test folder. I found a few problems:

1. It generated duplicated IMPROPER term.

    IMPROPERS
    CALTU  CALTU  CALTU  HALTU       1.1000  2   180.00
    HALTU  CALTU  CALTU  CALTU       1.1000  2   180.00

2. CHEQ keyword

You may want to add CHEQ keyword at the top of the PSF file. The current format that you are producing is CHEQ compatible, though CHEQ is not used, and CHARMM crashes. 

3. non-integer charge

After the conversion, the total charge of the system is 0.249. I'm not sure if this system actually has non-integer charge or this creeped up during the floating point conversion.

**Comment by swails** [comment]
@sunhwan -- thanks for the tips!  I fixed 1 and 2.  3 isn't a problem in the conversion -- the net charge of `benzene_cyclohexane_10_500.prmtop` is 0.249 (probably because of issues talked about in #268).

Can you try the latest commit?

**Comment by sunhwan** [comment]
@swails Great. I've confirmed CHARMM can read the psf/crd files produced by parmed. I'll test the energy later.

**Comment by swails** [comment]
Excellent, thanks!  If there are any problems parsing the parameter or topology files let me know.

**Comment by sunhwan** [comment]
@swails internal energies appears matched. Dihedral energy is slightly mismatched, but I need to dig more to see if this is really due to a bug or simply floating point conversion problem. But biggest problem is that, somehow, CHARMM doesn't generate any nonbond list if I read the converted PSF. I'm not sure why yet. I'll keep you posted.

**Comment by swails** [comment]
> Dihedral energy is slightly mismatched

How big is the difference?

> But biggest problem is that, somehow, CHARMM doesn't generate any nonbond list if I read the converted PSF

Huh... that's strange.  Did I add all of the cards to the NONBONDED line correctly?

**Comment by swails** [comment]
@sunhwan -- anything new on the CHARMM support?

**Comment by sunhwan** [comment]
@swails Sorry, I wasn't doing much. I'll get back to you soon.

**Comment by swails** [comment]
No worries.  Thanks!

**Comment by sunhwan** [comment]
@swails I've used CHARMM-GUI to generate AMBER and CHARMM files, then used ParmEd to convert the AMBER prmtop file to PSF to compare. There was two problem:

1. Atom type field column length is not correct. This bug didn't occur when I tried the example amber files from ParmEd distribution. 

screen shot 2015-08-05 at 10 42 05 am

2. NGRP NST2 section has to be properly populated to make the nonbond pairlist to work. If you don't want to have explicit groups, you have to at least set each individual molecule as a group, populate this column.

I've attached the files that I used for comparison below.

https://dl.dropboxusercontent.com/u/163146/Archive.zip

**Comment by davidlmobley** [comment]
@sunhwan - Also, it would be good to get the energies you were getting in
your earlier testing.

**Comment by swails** [comment]
> Atom type field column length is not correct. This bug didn't occur when I tried the example amber files from ParmEd distribution.

Unfortunately this is a limitation we're going to have to live with.  The Amber topology *cannot* store atom types larger than 4 characters long.  I could simply change the Fortran format string to something like 12a6 instead of 20a4, but the Amber MD engines make use of the fact that atom names, types, and residue names are 4 characters long so they have the same size as an integer (which is required for proper MPI broadcasting in the way that Amber currently works).

This is a *big* change, and not one that I can realistically make simply to accommodate CHARMM conventions.  So when you go from CHARMM -> Amber, you lose information in the atom type names.  Which means going *back* to CHARMM breaks after losing this information.

The moral of the story here is, round-tripping doesn't always work when translating between formats, since some formats store more or less information than others.

> NGRP NST2 section has to be properly populated to make the nonbond pairlist to work. If you don't want to have explicit groups, you have to at least set each individual molecule as a group, populate this column.

This is good to know.  If group definitions are available, I will use those.  Otherwise, I will assign each atom to its own group (I'll have to remind myself about this particular part of the PSF spec).  Thanks for the notes, I'll ping you when the group thing is done.

**Comment by sunhwan** [comment]
@swails truncated atom type is okay, but the charge column is shifted when it occured.

**Comment by swails** [comment]
> @swails truncated atom type is okay, but the charge column is shifted when it occured.

Ah!  So it needs to be 6-letter width?

**Comment by sunhwan** [comment]
@swails Yes. 6-letter atom type is the new extended PSF format.

**Comment by swails** [comment]
OK, it turns out I never really knew what the NGRP,NST2 section meant.  Can you help me out at all here?  What should I be doing when converting from a file that doesn't store any of this information?

**Comment by sunhwan** [comment]
@swails In CHARMM, group is typically a set of atoms that has neutral or integer charge. You can treat an entire molecule as a group if you don't have this group information. Each entry is consisted of 3 numbers, IGPBS, IGPTYP, and IMOVG. 

* IGPBS is the smallest atom number within a group (zero based).
* IGPTYP is 0 when all atoms in the group has zero charge, 1 when at least one atom has partial charges, and 2 when the total charge of the group is not zero.
* IMOVG is 1 when the atom position is fixed and 0 when the atom is not fixed.

**Comment by swails** [comment]
@sunhwan -- thanks for the tip!  Any idea what NST2 is (the second pointer)?

**Comment by sunhwan** [comment]
@swails I did energy comparison again, 

AMBER:

     BOND    =      180.5265  ANGLE   =      124.7918  DIHED      =        0.2939
     UB      =        0.7371  IMP     =        0.0000  CMAP       =        0.0000
     VDWAALS =      611.3718  EEL     =    -5034.7178  HBOND      =        0.0000
     1-4 VDW =       14.7151  1-4 EEL =       -0.1594  RESTRAINT  =        0.0000

CHARMM:

    ENER ENR:  Eval#     ENERgy      Delta-E         GRMS
    ENER INTERN:          BONDs       ANGLes       UREY-b    DIHEdrals    IMPRopers
    ENER EXTERN:        VDWaals         ELEC       HBONds          ASP         USER
     ----------       ---------    ---------    ---------    ---------    ---------
    ENER>        0  -4101.84435      0.00000      6.49871
    ENER INTERN>      180.52653    124.79182      0.00000      0.29386      0.00000
    ENER EXTERN>      626.08688  -5033.54345      0.00000      0.00000      0.00000
     ----------       ---------    ---------    ---------    ---------    ---------

The agreement is all good. There was a small deviation in the internal energies, bond, angle, etc. It turns out ParmEd truncates coordinates from double to single precision in CHARMM CRD files. This appears a bug in ParmEd and should be fixed.

Once I fixed the coordinates myself, the internal energies match exactly. There was another bug in ParmEd, which occurs when there is LENNARD_JONES_14_ACOEF (and BCOEF) in prmtop file. I think ParmEd flips the sign of those coefficient when it writes to prm file.

With cutoff=999, vdW and coulomb energies are well matched and only slightly different. For some reason, I can't match the vdW and ELEC energies when I set cutoff to a certain value, say 12 or 8. How does Amber treats cutoff? It doesn't use switching, right? I set both CUTON and CUTOFF as 12 in CHARMM, and the electrostatic energy is significantly different. Perhaps they are selecting nonbond pairs differently at a given cutoff?

**Comment by sunhwan** [comment]
@swails I don't know exactly, but it is related to ST2 water model. It appears ST2 water residues will have a special entry for this section as below.

              IGPTYP(IGRP)=3
              IMOVE(IQ-1)=-1
              IMOVE(IQ)=-1

**Comment by swails** [comment]
Ah, OK.  So I should always just set this to 0?

**Comment by swails** [comment]
> The agreement is all good. There was a small deviation in the internal energies, bond, angle, etc. It turns out ParmEd truncates coordinates from double to single precision in CHARMM CRD files. This appears a bug in ParmEd and should be fixed.

If there's any truncation occurring, it would have to be a result of a lossy conversion (like converting to an Amber ASCII restart file that prints coordinates to the format `%12.7f`).  I saw some documentation about the CHARMM coordinate file and print coordinates with the format `%20.10f` -- is that not correct?  Should I be using a different coordinate format with more decimals?

> Once I fixed the coordinates myself, the internal energies match exactly. There was another bug in ParmEd, which occurs when there is LENNARD_JONES_14_ACOEF (and BCOEF) in prmtop file. I think ParmEd flips the sign of those coefficient when it writes to prm file.

I never really understood the signs of the epsilon parameters in the CHARMM parameter file.  I think I recall a conversation where someone described what the negative sign meant, but I forgot what.

What sign *should* the epsilon parameters have?  They should be negative, correct?

> How does Amber treats cutoff? It doesn't use switching, right? I set both CUTON and CUTOFF as 12 in CHARMM, and the electrostatic energy is significantly different. Perhaps they are selecting nonbond pairs differently at a given cutoff?

Amber just uses a hard cutoff.  Are you sure that CHARMM isn't doing some kind of shifting or reaction field by default?  With the force-shift, doesn't the functional form of the nonbonded potential change?

**Comment by sunhwan** [comment]
@swails yes, coordinates are in %20.10f format. Currently it is printing them correctly but just the floating points are truncated after 4 decimal as in PDB file. The epsilons have minus sign. My bad for the cutoff part. I mistyped keyword for CUTON and CHARMM default for this value is CUTOFF-2. So, I was using a switched nonbonding option. Here's an updated energy comparison at 12 hard cutoff.

Amber:

     BOND    =      180.5265  ANGLE   =      124.7918  DIHED      =        0.2939
     UB      =        0.7371  IMP     =        0.0000  CMAP       =        0.0000
     VDWAALS =      614.4054  EEL     =    -3223.3598  HBOND      =        0.0000
     1-4 VDW =       14.7151  1-4 EEL =       -0.1594  RESTRAINT  =        0.0000

CHARMM:

    ENER ENR:  Eval#     ENERgy      Delta-E         GRMS
    ENER INTERN:          BONDs       ANGLes       UREY-b    DIHEdrals    IMPRopers
    ENER EXTERN:        VDWaals         ELEC       HBONds          ASP         USER
     ----------       ---------    ---------    ---------    ---------    ---------
    ENER>        0  -2281.84895      0.00000      6.68308
    ENER INTERN>      180.52653    124.79182      0.73708      0.29386      0.00000
    ENER EXTERN>      635.32096  -3223.51921      0.00000      0.00000      0.00000
     ----------       ---------    ---------    ---------    ---------    ---------

**Comment by swails** [comment]
The van der Waals is off by ~6 kcal/mol... that's pretty strange, isn't it?  Are there any NBFIX terms in this system?  Perhaps something with the long-range correction if this is a periodic system?

Any ideas why the van der Waals terms are so far off?  If there's a switching function employed for van der Waals in CHARMM, this would explain it as well.

**Comment by swails** [comment]
> @swails yes, coordinates are in %20.10f format. Currently it is printing them correctly but just the floating points are truncated after 4 decimal as in PDB file.

Can you show me a chunk of the CHARMM coordinate file and show me what you mean?

ParmEd should never truncate precision.  The only time I can see that happening is by reading in a file that has limited precision (same type of issue as the atom type truncation).

**Comment by sunhwan** [comment]
@swails 

CRD file

    * GENERATED BY PARMED (HTTPS://GITHUB.COM/PARMED/PARMED)
    *    
          1396  EXT
             1         1  BNZ       C3             13.8070000000       12.0830000000       12.5120000000
             2         1  BNZ       C2             12.7850000000       11.1760000000       12.4920000000
             3         1  BNZ       H3             14.8330000000       11.7400000000       12.4610000000
             4         1  BNZ       H2             13.0010000000       10.1120000000       12.4620000000

Amber inpcrd

     1396  0.0000000e+00
      13.8071045  12.0833177  12.5120063  12.7851954  11.1763934  12.4915096
      14.8330978  11.7398736  12.4608739  13.0008534  10.1122118  12.4623302
      11.4793257  11.5898833  12.4968291  11.1862022  12.9191915  12.5117393

**Comment by sunhwan** [comment]
@swails Wait... again, it is my bad. I didn't use inpcrd and used PDB for input coordinates. ugh.. Sorry about that.

**Comment by sunhwan** [comment]
@swails I think I figured the vdW issue. CHARMM default is FSWITCH and VFSWITCH, which switches force and the displayed energy is the integral of the forces. To match the nonbond option with amber, I needed to use SWTICH and VSWITCH. Below is the output.

    ENER ENR:  Eval#     ENERgy      Delta-E         GRMS
    ENER INTERN:          BONDs       ANGLes       UREY-b    DIHEdrals    IMPRopers
    ENER EXTERN:        VDWaals         ELEC       HBONds          ASP         USER
     ----------       ---------    ---------    ---------    ---------    ---------
    ENER>        0  -2288.04945      0.00000      6.68308
    ENER INTERN>      180.52653    124.79182      0.73708      0.29386      0.00000
    ENER EXTERN>      629.12046  -3223.51921      0.00000      0.00000      0.00000
     ----------       ---------    ---------    ---------    ---------    ---------

**Comment by swails** [comment]
This looks much better! I think we are getting close on more rigorous CHARMM support in ParmEd.

I just have to make sure the 1-4 epsilons are negative now, right?

**Comment by sunhwan** [comment]
I think so. I'll be on vacation from tomorrow and until next weekend, but will test more complex system if I have a chance.

**Comment by swails** [comment]
> I think so. I'll be on vacation from tomorrow and until next weekend, but will test more complex system if I have a chance.

Sounds good -- enjoy your vacation.  I've just made that change, so hopefully things should be good now.  I'll take the test case you sent me and add it to ParmEd when I get a chance.

Thanks!

**Comment by swails** [comment]
OK, I'm going to go ahead and merge this, since #343 is starting to depend on some of the changes made here.

@sunhwan -- I've made the 1-4 epsilons negative and should have patched up the improper handling (differences between periodic and harmonic impropers).  Those should hopefully be correctly handled now.  If there are more problems with this, please feel free to open a new issue and I'll address it in another PR.

This hopefully means we have full CHARMM support :) (minus the polarizable force field, since Drude particles aren't yet supported within ParmEd).

**Comment by swails** [comment]
@sunhwan -- any news on CHARMM support here?  How are energies matching up in your tests?

**Pull request merged**
