### PR TITLE
Addition of support to read the parameter files with XPLOR format in NAMD/CHARMM.

### PR DESCRIPTION
**Pull request by berkonat**
Added support to read the parameter files of .xplor format such as the parameter files in NAMD. In NAMD, CHARMM parameter files are converted to .xplor files that uses one-line definitions of bonds, angles and others. To extract the full database of parameters for all atom types that are not in topology/structure but in the given .par/.xplor file, dummy AtomTypes with index, mass, atomic number equal to -1 are also added. If all these changes seam OK to the developers, I would like to add them to the main stream with this pull/merge request. Thank you.

### CODE REVIEW

**Comment by swails** [comment]
Why'd you close this?

**Comment by berkonat** [comment]
I closed it for now. I found an issue in the code. It seams the changes break a test for Mol2, which I did not check. Is it OK to leave this merge request open until I fixed it?

**Comment by swails** [comment]
I won't merge it until you say you're ready.  GitHub is also telling me that this branch is out-of-date with master, so can you merge the latest code into your PR branch?

**Comment by hainm** [comment]
also need to delete "dist/ParmEd-3.0.0+13.ge835eee2-py3.6-macosx-10.12-x86_64.egg"

**Comment by berkonat** [comment]
Deleted the "dist" directory and merge the latest master with PR branch. I will check the issue on the parameter.py file and inform you when I am ready to merge it. Many thanks.

**Comment by berkonat** [comment]
Sorry for my previous Mol2 error comment. It seams that the error is on test_single_parameter.py file with "par_all22_prot.inp" input.

**Comment by swails** [comment]
Doesn't look like this will get picked back up.

**Pull request closed without merging**
